<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
$_product = $block->getProduct();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>

<div class="social-addthis">
    <span class="share"><?php echo __('Share:') ?></span>
    <a href="https://api.addthis.com/oexchange/0.8/forward/facebook/offer?url=<?php echo $_helper->productAttribute($_product, $_product->getProductUrl(), 'product_url'); ?>&amp;title=<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>" target="_blank">
        <span class="icon-facebook fa fa-facebook"></span>
    </a> 
    <a href="https://api.addthis.com/oexchange/0.8/forward/pinterest/offer?url=<?php echo $_helper->productAttribute($_product, $_product->getProductUrl(), 'product_url'); ?>&amp;title=<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>" target="_blank">
        <span class="icon-pinterest fa fa-pinterest-p"></span>
    </a>          
    <a href="https://api.addthis.com/oexchange/0.8/forward/google_plusone_share/offer?url=<?php echo $_helper->productAttribute($_product, $_product->getProductUrl(), 'product_url'); ?>&amp;title=<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>" target="_blank">
        <span class="icon-google fa fa-google-plus"></span>
    </a> 
    <a href="https://api.addthis.com/oexchange/0.8/forward/linkedin/offer?url=<?php echo $_helper->productAttribute($_product, $_product->getProductUrl(), 'product_url'); ?>&amp;title=<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>" target="_blank">
        <span class="icon-linkedin fa fa-linkedin"></span>
    </a>
    <a href="https://api.addthis.com/oexchange/0.8/forward/twitter/offer?url=<?php echo $_helper->productAttribute($_product, $_product->getProductUrl(), 'product_url'); ?>&amp;title=<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>" target="_blank">
        <span class="icon-twitter fa fa-twitter"></span>
    </a>
    <a href="https://api.addthis.com/oexchange/0.8/forward/email/offer?url=<?php echo $_helper->productAttribute($_product, $_product->getProductUrl(), 'product_url'); ?>&amp;title=<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>" target="_blank">
        <span class="icon-email"><img src="<?php echo $this->getViewFileUrl('images/email.jpg')?>"></span>
    </a>
</div>  
