<?php $_quote = $block->getQuote() ?>
<?php
$quoteCreateAt = $block->formatDate(
    $block->getOrderAdminDate($_quote->getCreatedAt()),
    \IntlDateFormatter::MEDIUM,
    true
);
$quoteUpdateAt = $block->formatDate(
    $_quote->getUpdateAt(),
    \IntlDateFormatter::MEDIUM,
    true
);
?>
<div class="page-main-actions">
    <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
        <div class="page-actions-inner" data-title="Chaz Kangeroo Hoodie">
            <div class="page-actions-buttons">
                <button id="back" title="Back" type="button" class="action- scalable back" onclick="location.href = '<?php echo $block->getBackUrl(); ?>;'" data-ui-id="back-button">
                    <span>Back</span>
                </button>
            </div>
        </div>
    </div>
</div>
<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title"><?php echo __('Carts and Account Information') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo __('Carts Information') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                    <tbody>
                    <tr>
                        <th><?php echo __('Careate Date') ?></th>
                        <td><?php echo $quoteCreateAt; ?></td>
                    </tr>
                    <tr>
                        <th><?php echo __('Update Date') ?></th>
                        <td><?php echo $quoteUpdateAt; ?></td>
                    </tr>
                    <tr>
                        <th><?php echo __('Purchased From') ?></th>
                        <td><?php echo $block->getQuoteStoreName() ?></td>
                    </tr>
                    <tr>
                        <th><?php echo __('Placed from IP') ?></th>
                        <td><?php echo $_quote->getRemoteIp() ?></td>
                    </tr>
                    </tbody></table>
            </div>
        </div>

        <div class="admin__page-section-item order-account-information">
            <div class="admin__page-section-item-title">
                <span class="title">Account Information</span>
                <div class="actions"></div>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table">
                    <tbody><tr>
                        <th><?php echo __('Customer Name') ?></th>
                        <td>
                            <a href="<?php echo $block->getCustomerViewUrl() ?>" target="_blank">
                                <span><?php echo $block->escapeHtml($block->getCustomerName()) ?></span>
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <th><?php echo __('Email') ?></th>
                        <td><a href="mailto:<?php $block->escapeHtml($_quote->getCustomerEmail()) ?>"><?php $block->escapeHtml($_quote->getCustomerEmail()) ?></a></td>
                    </tr>
                    <?php if ($_groupName = $block->getCustomerGroupName()) : ?>
                        <tr>
                            <th><?php /* @escapeNotVerified */ echo __('Customer Group') ?></th>
                            <td><?php /* @escapeNotVerified */ echo $_groupName ?></td>
                        </tr>
                    <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<section class="admin__page-section order-addresses">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Cart Items') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__table-wrapper">
            <table class="data-table admin__table-primary edit-order-table">
                <thead>
                <tr class="headings">
                    <th class="col-product"><span><?php /* @escapeNotVerified */ echo __('Product') ?></span></th>
                    <th class="col-product"><span><?php /* @escapeNotVerified */ echo __('Sku') ?></span></th>
                    <th class="col-price-original"><span><?php /* @escapeNotVerified */ echo __('Original Price') ?></span></th>
                    <th class="col-price"><span><?php /* @escapeNotVerified */ echo __('Price') ?></span></th>
                    <th class="col-ordered-qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></th>
                    <th class="col-tax-amount"><span><?php /* @escapeNotVerified */ echo __('Tax Amount') ?></span></th>
                    <th class="col-tax-percent"><span><?php /* @escapeNotVerified */ echo __('Tax Percent') ?></span></th>
                    <th class="col-discont"><span><?php /* @escapeNotVerified */ echo __('Discount Amount') ?></span></th>
                </tr>
                </thead>
                <?php $_items = $block->getItemsCollection();?>
                <?php $i = 0; foreach ($_items as $_item):?>
                    <?php if ($_item->getParentItem()) {
                        continue;
                    } else {
                        $i++;
                    }?>
                    <tbody class="<?php /* @noEscape */ echo $i%2 ? 'even' : 'odd' ?>">
                        <td><?php echo $_item->getName() ?></td>
                        <td><?php echo $_item->getSku() ?></td>
                        <td><?php echo $_item->getBasePrice(); ?></td>
                        <td><?php echo $_item->getPrice(); ?></td>
                        <td><?php echo $_item->getQty(); ?></td>
                        <td><?php echo $_item->getTaxAmount(); ?></td>
                        <td><?php echo $_item->getTaxPercent(); ?></td>
                        <td><?php echo $_item->getDiscountAmount(); ?></td>
                    </tbody>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</section>