<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */


?>

<div class="block <?php /* @escapeNotVerified */ echo $block->getBlockCss(); ?>">
    <div class="title <?php /* @escapeNotVerified */ echo $block->getBlockCss();?>-title" data-mage-init='{"toggleAdvanced": {"toggleContainers": "#<?php /* @escapeNotVerified */ echo $block->getBlockCss(); ?>", "selectorsToggleClass": "active"}}'>
        <strong><?php /* @escapeNotVerified */ echo $block->getBlockTitle(); ?></strong>
    </div>
    <div class="content <?php /* @escapeNotVerified */ echo $block->getBlockCss(); ?>-content" id="<?php /* @escapeNotVerified */ echo $block->getBlockCss(); ?>">
        <?php echo $block->getChildHtml(); ?>
    </div>
</div>
<div id="cus-log-out" class="block block-collapsible-nav">
	<ul class="nav items">
		<li class="nav item" id="logout-li">
			<a href="<?php echo $this->getUrl('customer/account/logout') ?>">Log Out</a>
		</li>
	</ul>
</div>
