<div id="addcartbox" style="display:none">
    <div class="addcartbox_content">
        <p class="success">Item&nbsp;successfully&nbsp;added&nbsp;to&nbsp;your&nbsp;cart!</p>
        <ul class="go-shoppinglist">
            <li>
                <img class="gw-product-ajax-img" id="gw-product-ajax-img" src="">
                <dl>
                    <div id="new-details">
                        <dt></dt>
                    </div>
                    <dd><div class="price" >price:$<span id="gw-product-ajax-price"></span></div><a href="/checkout/cart/" class="viewmore">view cart</a><a href="/checkout/" class="addcartbox_checkout">checkout</a></dd>
                </dl>
            </li>
            <!--            <a href="javascript:;" id="addcart_close" onclick="addcartClose();">x</a>-->
        </ul>

    </div>
</div>





