<div class="shopping-step">
    <ul>
        <li class="step _active step1">
            <span class="num">Step 1:</span>
            <span class="stepdes">Shipping Cart</span>
        </li>

        <li class="step step2">
            <span class="num">Step 2:</span>
            <span class="stepdes">Checkout</span>
        </li>
        <li class="step step3">
            <span class="num">Step 3:</span>
            <span class="stepdes">Payments</span>
        </li>
    </ul>
</div>