<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="add-cart-content">
    <ul class="add-cart-content-first">
        <li><strong>Useful tips for your Shopping Cart:</strong></li>
        <li>1.You can add up to 10000 products in your Shopping Cart.</li>
        <li>2.Products will remain in your shopping Cart for the parmanent.</li>
        <li>3.Products can be added to your Shopping Cart whether your're logged in or not.</li>
    </ul>
</div>