<?php
use Magento\Framework\App\Action\Action;
?>

<?php
$_productCollection = $block->getProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    $viewMode = 'grid';
    $image = 'category_page_grid';
    $showDescription = false;
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $classid = md5(json_encode($block->getData()));
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="widget block-products-list <?php /* @escapeNotVerified */ echo $viewMode; ?>">
		<?php if ($title):?>
		<div class="block-title">
                  <strong><?php /* @escapeNotVerified */ echo $title; ?></strong>    
                  <div class="line"></div>
                </div>
		<?php endif ?>
		<div class="catelog_product block-content <?php echo $classid ?>">
			<div class="index_content wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> product_list">
				<?php $iterator = 1; ?>				
				<ol class="list items product-items">
				    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
				    <?php foreach ($_productCollection as $_product): ?>
				        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
				        <div class="product-item-info" data-container="product-grid">
				            <?php
				            $productImage = $block->getImage($_product, $image);
				            if ($pos != null) {
				                $position = ' style="left:' . $productImage->getWidth() . 'px;'
				                    . 'top:' . $productImage->getHeight() . 'px;"';
				            }
				            ?>
				            <?php if($block->isShow('thumb')): ?>
				            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1" title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>">
				                <?php echo $productImage->toHtml(); ?>
				            </a>
				            <?php endif ?>
				            <div class="product details product-item-details">
				                <?php
				                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
				                ?>
				                <?php if($block->isShow('name')): ?>
				                <strong class="product name product-item-name">
				                    <a class="product-item-link"
				                       href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
				                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
				                    </a>
				                </strong>
				                <?php endif ?>
				                <?php if($block->isShow('review')): ?>
				                <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
				                <?php endif ?>
				                <?php if($block->isShow('price')): ?>
				                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product);?>
				                <?php endif ?>
				                <div class="product-item-inner">
				                    <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
				                    	<?php if($block->isShow('addtocart')): ?>
				                        <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
				                            <?php if ($_product->isSaleable()): ?>
				                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
				                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
				                                    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
				                                    <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
				                                    <?php echo $block->getBlockHtml('formkey')?>
				                                    <button type="submit"				                                           
				                                            class="action tocart primary">
				                                            <i class="fa fa-shopping-cart"></i>
                                                                            <span class="prompt"><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
				                                    </button>
				                                </form>
				                            <?php else: ?>
				                                <?php if ($_product->getIsSalable()): ?>
				                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
				                                <?php else: ?>
				                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
				                                <?php endif; ?>
				                            <?php endif; ?>
				                        </div>
				                        <?php endif ?>
				                        <?php if($block->isShow('addto')): ?>
				                        <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
				                        <?php
				                            $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
				                            ?>
				                            <a href="#"
				                               class="action"				                              
				                               aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
				                               data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
				                               role="button">
				                               <i class="fa fa-signal"></i>
                                                               <span class="prompt"><?php /* @escapeNotVerified */ echo __('Compare') ?></span>
				                            </a>
				                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
				                                <a href="#"
				                                   class="action wishlist"				                                   
				                                   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
				                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
				                                   data-action="add-to-wishlist"
				                                   role="button">
				                                   <i class="fa fa-heart-o"></i>
                                                                   <span class="prompt"><?php /* @escapeNotVerified */ echo __('Wish List') ?></span>
				                                </a>
				                            <?php endif; ?>

				                        </div>
				                        <?php endif ?>
				                    </div>
				                </div>
				            </div>
				        </div>
				        <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
				    <?php endforeach; ?>
				</ol>
			</div>
			<?php echo $block->getToolbarHtml() ?>
			<?php if (!$block->isRedirectToCartEnabled()) : ?>
				<script type="text/x-magento-init">
				{
				    "[data-role=tocart-form], .form.map.checkout": {
				        "catalogAddToCart": {}
				    }
				}
				</script>
			<?php endif; ?>
		</div>
	</div>
<?php endif; ?>

  