<?php
/**
* Copyright 2016 aheadWorks. All rights reserved.
* See LICENSE.txt for license details.
*/

// @codingStandardsIgnoreFile

/* @var $block \Magento\Sales\Block\Adminhtml\Items\Column\DefaultColumn */
?>
<?php $block->setPriceDataObject($block->getItem()) ?>
<?php echo /* @noEscape */ $block->displayPriceAttribute('aw_reward_points_amount') ?> (<?php /* @noEscape */ echo $block->getItem()->getAwRewardPoints() * 1 ?>)
