<?php
use Magento\Framework\App\Action\Action;
?>

<?php
$_productCollection = $block->getProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    $viewMode = 'grid';
    $image = 'category_page_grid';
    $showDescription = false;
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $classid = md5(json_encode($block->getData()));
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="block widget block-products-list <?php /* @escapeNotVerified */ echo $viewMode; ?>">
		<?php if ($title):?>
		<div class="block-title">
			<div class="dashednline"></div>
            <strong><?php /* @escapeNotVerified */ echo $title; ?></strong>
        </div>
		<?php endif ?>
		<div class="index_product block-content <?php echo $classid ?> owl-carousel owl-theme">
			<div  id="hotsale" class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> product_list">
				<?php $iterator = 1; ?>
				<ol class="products list items product-items">
				    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
				    <?php foreach ($_productCollection as $_product): ?>
				        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
				        <div class="product-item-info" data-container="product-grid">
				            <?php
				            $productImage = $block->getImage($_product, $image);
				            if ($pos != null) {
				                $position = ' style="left:' . $productImage->getWidth() . 'px;'
				                    . 'top:' . $productImage->getHeight() . 'px;"';
				            }
				            ?>
				            <?php if($block->isShow('thumb')): ?>
				            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1" title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>">
				                <?php echo $productImage->toHtml(); ?>
				            </a>
				            <?php endif ?>
				            <div class="product details product-item-details">
				                <?php
				                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
				                ?>
				                <?php if($block->isShow('name')): ?>
				                <strong class="product name product-item-name">
				                    <a class="product-item-link"
				                       href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
				                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
				                    </a>
				                </strong>
				                <?php endif ?>

                                <?php if($block->getReviewsSummaryHtml($_product, $templateType)):?>
                                    <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>                                                   
                                <?php else:?>					                
                                    <div class="product-reviews-summary short">
                                        <div class="rating-summary">
                                            <span class="label"><span>Rating:</span></span>
                                            <div class="rating-result" title="0%">
                                                <span style="width:0%"><span>0%</span></span>
                                            </div>
                                        </div>
                                        <div class="reviews-actions" style="display:inline-block">
                                            &nbsp;<span>0&nbsp;Reviews</span>
                                        </div>
                                    </div>
				                
                                <?php endif ?>	
				                <?php if($block->isShow('price')): ?>
				                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product);?>
				                <?php endif ?>
				                <div class="product-item-inner">
				                    <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
				                        <?php if($block->isShow('addto')): ?>
				                        <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
				                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
				                                <a href="#"
				                                   class="action wishlist"				                                   
				                                   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
				                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
				                                   data-action="add-to-wishlist"
				                                   role="button">
				                                   <i class="fa fa-heart-o"></i>
                                                                   <span class="prompt"><?php /* @escapeNotVerified */ echo __('Wish List') ?></span>
				                                </a>
				                            <?php endif; ?>
				                        </div>
				                        <?php endif ?>
				                    </div>
				                </div>
				            </div>
				        </div>
				        <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
				    <?php endforeach; ?>
				</ol>
			</div>
			<?php echo $block->getToolbarHtml() ?>
			<?php if (!$block->isRedirectToCartEnabled()) : ?>
				<script type="text/x-magento-init">
				{
				    "[data-role=tocart-form], .form.map.checkout": {
				        "catalogAddToCart": {}
				    }
				}
				</script>
			<?php endif; ?>
		</div>
	</div>
            <script type="text/javascript">
                    require(['jquery','Codazon_ProductFilter/owlcarousel/owl.carousel','domReady!'],function($){
                            var owl = $('.index_product .product-items');
                            if(owl.length){   
                                owl.owlCarousel({
                                                    loop: false,
                                                    margin: 10,
                                                    responsiveClass: true,
                                                    nav: true,
                                                    dots: false,
                                                    responsive:{
                                                            0:{items: 	2},
                                                            320:{items:	2},
                                                            400:{items:	2, slideBy: 2},
                                                            768:{items:	2, slideBy: 2},
                                                            980:{items:	4, slideBy: 4},
                                                            1200:{items: 4, slideBy: 4}
                                                    }		
                                            });         
                            }
                        });
            </script>
<?php endif; ?>

  